spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ezworks}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
    username: ${DB_USER:ezworks}
    password: ${DB_PASSWORD:ezworks123}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.ezworks: DEBUG
    org.springframework.security: INFO
